"""Built-in structured ICAWS HRC catalog (code-native)."""

from typing import Dict, List

HRC_ALERT_DEFS: List[Dict[str, object]] = [{'name': 'AIR DATA DEGD',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3410013101011']},
 {'name': 'AIR DATA FAIL',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3410013101011']},
 {'name': 'AIR DATA HEATER',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010100010 - 3410013101011']},
 {'name': 'AMD FAIL',
  'severities': ['caution'],
  'system': 'MSP',
  'subsystem': 'PMD',
  'detail_lines': ['4233210002001, 4233210202001']},
 {'name': 'BATT FAIL 270V',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'BAT_270',
  'detail_lines': ['2432010100324, 2432011104124, 2432011106217']},
 {'name': 'BATT FAIL 28V',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'BAT_28',
  'detail_lines': ['2431010100309, 2431011104122, 2431011106216']},
 {'name': 'BATT LO 270V',
  'severities': ['warning'],
  'system': 'EPS',
  'subsystem': 'BAT_270',
  'detail_lines': ['2432010103793']},
 {'name': 'BATT LO 28V',
  'severities': ['caution', 'warning'],
  'system': 'EPS',
  'subsystem': 'BAT_28',
  'detail_lines': ['CAUTION when between 5-10% or lower, WARNING when 5% or lower.', '2431011103788']},
 {'name': 'BINGO', 'severities': ['advisory'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'BLD LEAK ENG',
  'severities': ['warning'],
  'system': 'PTMS',
  'subsystem': 'BLEED',
  'detail_lines': ['2100000100144, 2600000100050, 2600000100092']},
 {'name': 'BLD LEAK IPP',
  'severities': ['warning'],
  'system': 'PTMS',
  'subsystem': 'BLEED',
  'detail_lines': ['2100000100144, 2600000100014, 2600000100101']},
 {'name': 'BOS LO',
  'severities': ['caution'],
  'system': 'LIF_SUP',
  'subsystem': 'BOS',
  'detail_lines': ['Replace "BOS LOW" with this.', '3500001100302']},
 {'name': 'BOS SERVICE',
  'severities': ['advisory'],
  'system': 'LIF_SUP',
  'subsystem': 'BOS',
  'detail_lines': ['Trigger when BOS is below 280L', '3500000100306']},
 {'name': 'BRAKE DEGD',
  'severities': ['caution'],
  'system': 'GEAR',
  'subsystem': 'BRAKES',
  'detail_lines': ['3200000100450 - 3243000100143']},
 {'name': 'BRAKE FAIL',
  'severities': ['caution'],
  'system': 'GEAR',
  'subsystem': 'BRAKES',
  'detail_lines': ['3243000100142, 3243000100143']},
 {'name': 'BUR DEGD',
  'severities': ['advisory'],
  'system': 'COM_NAV',
  'subsystem': 'CNI',
  'detail_lines': ['4800000000001 - 4800001980005']},
 {'name': 'BUR FAIL',
  'severities': ['advisory'],
  'system': 'COM_NAV',
  'subsystem': 'CNI',
  'detail_lines': ['4800000000001 - 4800001980005']},
 {'name': 'CABIN PRESS',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'CABIN',
  'detail_lines': ['2116010100565, 2116010100566']},
 {'name': 'CANOPY UNLOCKED',
  'severities': ['advisory', 'caution'],
  'system': 'PTMS',
  'subsystem': 'CABIN',
  'detail_lines': ['4239000180001']},
 {'name': 'CM DEGD',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'CM',
  'detail_lines': ['9920000100010 - 9920000208006']},
 {'name': 'CM DOOR',
  'severities': ['caution'],
  'system': 'EW',
  'subsystem': 'CM',
  'detail_lines': ['9920000000013 - 9920000202000']},
 {'name': 'CM FAIL',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'CM',
  'detail_lines': ['9920000100010 - 9920000202000']},
 {'name': 'CM FAIL - IFF',
  'severities': ['caution'],
  'system': 'EW',
  'subsystem': 'CM',
  'detail_lines': ['4800000001058 - 4800000204002']},
 {'name': 'CNI FAIL - RALT',
  'severities': ['advisory'],
  'system': 'CNI',
  'subsystem': 'CNI',
  'detail_lines': ['4800000001071 - 4800000202223']},
 {'name': 'CNI FAIL - TACAN',
  'severities': ['advisory'],
  'system': 'CNI',
  'subsystem': 'CNI',
  'detail_lines': ['480000001058 - 48000000201507']},
 {'name': 'CNI FAIL ILS',
  'severities': ['advisory'],
  'system': 'CNI',
  'subsystem': 'CNI',
  'detail_lines': ['480000001082 - 48000000201544']},
 {'name': 'CNI FAIL INT',
  'severities': ['advisory'],
  'system': 'CNI',
  'subsystem': 'CNI',
  'detail_lines': ['480000001200 - 48000000204006']},
 {'name': 'CNI FAIL L16 IPF',
  'severities': ['advisory'],
  'system': 'CNI',
  'subsystem': 'CNI',
  'detail_lines': ['480000002411 - 48000000201509']},
 {'name': 'CNI RACK FAIL A',
  'severities': ['caution'],
  'system': 'CNI',
  'subsystem': 'CNI',
  'detail_lines': ['480000000165 - 48000000202123']},
 {'name': 'CNI RACK FAIL B',
  'severities': ['caution'],
  'system': 'CNI',
  'subsystem': 'CNI',
  'detail_lines': ['480000000168 - 48000000202124']},
 {'name': 'CNVTR FAIL DUAL',
  'severities': ['caution', 'warning'],
  'system': 'EPS',
  'subsystem': 'EDU 1',
  'detail_lines': ['2431020103558, 2431021103559']},
 {'name': 'CNVTR HOT',
  'severities': ['warning'],
  'system': 'EPS',
  'subsystem': 'EDU 1',
  'detail_lines': ['2431020190328, 2431021190329']},
 {'name': 'COLD LOOP TEMP',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'COLDLL',
  'detail_lines': ['2100000190009 - 2116010100325']},
 {'name': 'CONV HALT',
  'severities': ['caution', 'warning'],
  'system': 'PTMS',
  'subsystem': 'COLDLL',
  'detail_lines': ['4570003787006']},
 {'name': 'COOL DEGD EHA',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'COLDLL',
  'detail_lines': ['2100000010016 - 2100000190102']},
 {'name': 'COOL DEGD FCS CH',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'COLDLL',
  'detail_lines': ['2100000190004']},
 {'name': 'COOL FAIL EHA',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'COLDLL',
  'detail_lines': ['2100000100143 - 2100000190008']},
 {'name': 'COOL FAIL ENG',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'COLDLL',
  'detail_lines': ['2100000100081 - 2100000100132']},
 {'name': 'COOL FAIL FCS CH',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'COLDLL',
  'detail_lines': ['2100000010015 - 2100000190080']},
 {'name': 'COOL FAIL IPP',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'COLDLL',
  'detail_lines': ['2100000100063 - 2100000100106']},
 {'name': 'DAS DEGD',
  'severities': ['advisory'],
  'system': 'DAS',
  'subsystem': 'DAS',
  'detail_lines': ['9930010101900 - 9930010106913']},
 {'name': 'DAS FAIL',
  'severities': ['advisory'],
  'system': 'DAS',
  'subsystem': 'DAS',
  'detail_lines': ['9930010101900 - 9930010106920']},
 {'name': 'DAS HOT BA',
  'severities': ['advisory'],
  'system': 'DAS',
  'subsystem': 'DAS',
  'detail_lines': ['9930010105900, 9930010105910']},
 {'name': 'DAS HOT BF',
  'severities': ['advisory'],
  'system': 'DAS',
  'subsystem': 'DAS',
  'detail_lines': ['9930010104900, 9930010104910']},
 {'name': 'DAS HOT LS',
  'severities': ['advisory'],
  'system': 'DAS',
  'subsystem': 'DAS',
  'detail_lines': ['9930010103900, 9930010103910']},
 {'name': 'DAS HOT RS',
  'severities': ['advisory'],
  'system': 'DAS',
  'subsystem': 'DAS',
  'detail_lines': ['9930010102900, 9930010105210']},
 {'name': 'DAS HOT TA',
  'severities': ['advisory'],
  'system': 'DAS',
  'subsystem': 'DAS',
  'detail_lines': ['9930010106900, 9930010106910']},
 {'name': 'DAS HOT TF',
  'severities': ['advisory'],
  'system': 'DAS',
  'subsystem': 'DAS',
  'detail_lines': ['9930010101900, 9930010101910']},
 {'name': 'DISPLAY DEGD',
  'severities': ['caution'],
  'system': 'DISPL',
  'subsystem': 'PCD_L or PCD_R (Random)',
  'detail_lines': ['4220020100001 - 4220020190005, 4600001210335 - 4600001210133']},
 {'name': 'DISPLAY HOT HMD', 'severities': ['caution'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'ENG COMM DEGD',
  'severities': ['caution'],
  'system': 'PROP',
  'subsystem': 'FADEC',
  'detail_lines': ['2700000299101 - 2700000299302, 7610010793030 - 7610020794034']},
 {'name': 'ENG COMM FAIL',
  'severities': ['warning'],
  'system': 'PROP',
  'subsystem': 'FADEC',
  'detail_lines': ['2700000299101 - 2700000299302']},
 {'name': 'ENG CTRL FAIL',
  'severities': ['warning'],
  'system': 'PROP',
  'subsystem': 'FADEC',
  'detail_lines': ['7530010792002 - 7530040792003']},
 {'name': 'ENG DEGD',
  'severities': ['caution'],
  'system': 'PROP',
  'subsystem': 'FADEC',
  'detail_lines': ['7310020790001 - 7320160790001']},
 {'name': 'ENG FADEC FAIL',
  'severities': ['caution'],
  'system': 'PROP',
  'subsystem': 'FADEC',
  'detail_lines': ['4570001892020, 7610010792001 - 7610020794044']},
 {'name': 'ENG FADEC HOT',
  'severities': ['caution'],
  'system': 'PROP',
  'subsystem': 'FADEC',
  'detail_lines': ['7610010793028, 7610020794028']},
 {'name': 'ENG LAST CH',
  'severities': ['caution'],
  'system': 'PROP',
  'subsystem': 'PERF',
  'detail_lines': ['7320060793001 - 7320090792002']},
 {'name': 'ENG LIMIT',
  'severities': ['caution'],
  'system': 'PROP',
  'subsystem': 'PERF',
  'detail_lines': ['7200010790001, 7320060790009 - 7320060790019']},
 {'name': 'ENG OIL',
  'severities': ['caution'],
  'system': 'PROP',
  'subsystem': 'ENGOIL',
  'detail_lines': ['7230010796001, 7230010796002, 7930020792002']},
 {'name': 'ENG OIL HOT',
  'severities': ['caution'],
  'system': 'PROP',
  'subsystem': 'ENGOIL',
  'detail_lines': ['7230010796003']},
 {'name': 'ENG STALL',
  'severities': ['caution'],
  'system': 'PROP',
  'subsystem': 'PERF',
  'detail_lines': ['7200010790002 - 7200010790015']},
 {'name': 'ENG THRUST LO',
  'severities': ['caution'],
  'system': 'PROP',
  'subsystem': 'FADEC',
  'detail_lines': ['7200010790005, 7310010790002, 7500100790004']},
 {'name': 'EOTS DEGD',
  'severities': ['advisory'],
  'system': 'EOTS',
  'subsystem': 'EOTS',
  'detail_lines': ['9940000000000 - 9949999999999']},
 {'name': 'EOTS FAIL',
  'severities': ['advisory'],
  'system': 'EOTS',
  'subsystem': 'EOTS',
  'detail_lines': ['2400000190023, 4221000100980, 9940000303452']},
 {'name': 'EPS COMM DEGD',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'ICC',
  'detail_lines': ['2400000190202 - 2400000190205']},
 {'name': 'EPS DEGD',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'ICC',
  'detail_lines': ['2400003102269 - 2460031100283']},
 {'name': 'EPS FAIL 270V',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'BAT_270',
  'detail_lines': ['2460010100286 - 2460011100287']},
 {'name': 'EPS FAIL 28V',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'BAT_28',
  'detail_lines': ['2460030100274 - 2460031100275']},
 {'name': 'EPS FAULT',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'ICC',
  'detail_lines': ['2460020100278, 2460021100279, 2460030100282']},
 {'name': 'EW DEGD',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'ESM',
  'detail_lines': ['9910000000100 - 9910000207800']},
 {'name': 'EW FAIL',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'ESM',
  'detail_lines': ['9910000000100 - 9910000207800']},
 {'name': 'FCS CG DEGD',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS CH FAIL A',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS CH FAIL B',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS CH FAIL C',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS CH HOT A',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS CH HOT B',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS CH HOT C',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS DATA FAIL',
  'severities': ['warning'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS DEGD',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS EHA HOT',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'EHAS',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS FAULT',
  'severities': ['advisory'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS LAST CH',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS POWER LIMIT',
  'severities': ['caution', 'warning'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS SURFACE DEGD',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS SURFACE FAIL',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FCS VEL DEGD',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['3410010090001 - 3420000200240']},
 {'name': 'FIRE CM BAY',
  'severities': ['warning'],
  'system': 'FPS',
  'subsystem': 'DET_EB',
  'detail_lines': ['2600000100043']},
 {'name': 'FIRE ENG',
  'severities': ['warning'],
  'system': 'FPS',
  'subsystem': 'DET_DB',
  'detail_lines': ['2600000100081']},
 {'name': 'FIRE GEAR',
  'severities': ['warning'],
  'system': 'FPS',
  'subsystem': 'DET_IBL',
  'detail_lines': ['2600000100037']},
 {'name': 'FIRE IPP',
  'severities': ['warning'],
  'system': 'FPS',
  'subsystem': 'DET_IPP',
  'detail_lines': ['2600000100044']},
 {'name': 'FIRE WPN BAY L',
  'severities': ['warning'],
  'system': 'FPS',
  'subsystem': 'DET_EB',
  'detail_lines': ['2600000100047']},
 {'name': 'FIRE WPN BAY R',
  'severities': ['warning'],
  'system': 'FPS',
  'subsystem': 'DET_EB',
  'detail_lines': ['2600000100080']},
 {'name': 'FLAMEOUT',
  'severities': ['warning'],
  'system': 'PROP',
  'subsystem': 'FADEC',
  'detail_lines': ['7200010790023, 730010790003']},
 {'name': 'FPS DETECT DEGD',
  'severities': ['caution'],
  'system': 'FPS',
  'subsystem': 'Random: DET_DB, DET_EB, DET_ENG, DET_IBL, DET_IPP',
  'detail_lines': ['2600000110026 - 2631028100212']},
 {'name': 'FPS DISCHARGE',
  'severities': ['caution'],
  'system': 'FPS',
  'subsystem': 'SUP_DB',
  'detail_lines': ['2600000100046']},
 {'name': 'FPS SUPRESS DEGD',
  'severities': ['caution'],
  'system': 'FPS',
  'subsystem': 'SUP_DB',
  'detail_lines': ['2622010100027']},
 {'name': 'FUEL BOOST LO',
  'severities': ['caution'],
  'system': 'FUEL',
  'subsystem': 'FPRESS',
  'detail_lines': ['2820000100020']},
 {'name': 'FUEL BOOST PUMP',
  'severities': ['caution'],
  'system': 'FUEL',
  'subsystem': 'FPRESS',
  'detail_lines': ['2820000100020']},
 {'name': 'FUEL DEGD',
  'severities': ['caution'],
  'system': 'FUEL',
  'subsystem': 'FPRESS',
  'detail_lines': ['2820000100007 - 2820000108382']},
 {'name': 'FUEL DUMP OPEN',
  'severities': ['caution'],
  'system': 'FUEL',
  'subsystem': 'DUMP',
  'detail_lines': ['2820000100007 - 2820000108382']},
 {'name': 'FUEL FEED TANK',
  'severities': ['caution'],
  'system': 'FUEL',
  'subsystem': 'FEED',
  'detail_lines': ['NO HRC']},
 {'name': 'FUEL HOT', 'severities': ['caution'], 'system': 'FUEL', 'subsystem': 'THRMAL', 'detail_lines': ['NO HRC']},
 {'name': 'FUEL RECIRC',
  'severities': ['caution'],
  'system': 'FUEL',
  'subsystem': 'TRNSFR',
  'detail_lines': ['2820000100007 - 2820000108382']},
 {'name': 'FUEL TANK PRESS',
  'severities': ['caution'],
  'system': 'FUEL',
  'subsystem': 'FPRESS',
  'detail_lines': ['2820000100007 - 2820000108382']},
 {'name': 'GCAS ALT DEGD',
  'severities': ['advisory'],
  'system': 'COM_NAV',
  'subsystem': 'PSCTS',
  'detail_lines': ['NO HRC']},
 {'name': 'GCAS FAIL',
  'severities': ['advisory'],
  'system': 'COM_NAV',
  'subsystem': 'PSCTS',
  'detail_lines': ['NO HRC']},
 {'name': 'GEAR DEGD',
  'severities': ['caution'],
  'system': 'GEAR',
  'subsystem': 'Random: GEAR_L, GEAR_N, GEAR_R',
  'detail_lines': ['NO HRC']},
 {'name': 'GEAR FAIL',
  'severities': ['caution'],
  'system': 'GEAR',
  'subsystem': 'Random: GEAR_L, GEAR_N, GEAR_R',
  'detail_lines': ['NO HRC']},
 {'name': 'GEN FAIL 1',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'ICC',
  'detail_lines': ['2432030100100 - 2432030105423']},
 {'name': 'GEN FAIL 1&2', 'severities': ['warning'], 'system': 'EPS', 'subsystem': 'ICC', 'detail_lines': ['NO HRC']},
 {'name': 'GEN FAIL 2',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'ICC',
  'detail_lines': ['2432030100100 - 2432030105423']},
 {'name': 'GEN FAIL 3',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'ICC',
  'detail_lines': ['2432030100100 - 2432030105423']},
 {'name': 'GEN HOT 3',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'ICC',
  'detail_lines': ['2432030100100 - 2432030105423']},
 {'name': 'GEN OIL FAIL 1&2',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'ICC',
  'detail_lines': ['2432030100100 - 2432030105423']},
 {'name': 'GEN OIL HOT 1&2',
  'severities': ['caution'],
  'system': 'EPS',
  'subsystem': 'ICC',
  'detail_lines': ['2432030100100 - 2432030105423']},
 {'name': 'GPS DEGD',
  'severities': ['advisory'],
  'system': 'COM_NAV',
  'subsystem': 'GPS',
  'detail_lines': ['4821011000001 - 4821011540003']},
 {'name': 'GPS FAIL',
  'severities': ['advisory'],
  'system': 'COM_NAV',
  'subsystem': 'GPS',
  'detail_lines': ['4821011000001 - 4821011540003']},
 {'name': 'GPS NO KEYS',
  'severities': ['advisory'],
  'system': 'COM_NAV',
  'subsystem': 'GPS',
  'detail_lines': ['4821011000001 - 4821011540003']},
 {'name': 'GUN DOOR OPEN',
  'severities': ['advisory'],
  'system': 'GUN',
  'subsystem': 'GUN',
  'detail_lines': ['9450000100053']},
 {'name': 'HDG DISAGREE',
  'severities': ['caution'],
  'system': 'COM_NAV',
  'subsystem': 'CNI',
  'detail_lines': ['NO HRC']},
 {'name': 'HMD BST FAULT',
  'severities': ['advisory'],
  'system': 'DISPL',
  'subsystem': 'HMDS',
  'detail_lines': ['4232001102802']},
 {'name': 'HOOK DEGD', 'severities': ['caution'], 'system': 'GEAR', 'subsystem': 'HOOK', 'detail_lines': ['NO HRC']},
 {'name': 'HOOK FAIL', 'severities': ['caution'], 'system': 'GEAR', 'subsystem': 'HOOK', 'detail_lines': ['NO HRC']},
 {'name': 'HOTAS FAULT',
  'severities': ['advisory'],
  'system': 'FCS',
  'subsystem': 'STICK',
  'detail_lines': ['2713012101032 - 2713012101202']},
 {'name': 'HYD COLD',
  'severities': ['caution'],
  'system': 'HYD',
  'subsystem': 'Random: HYD_A, HYD_B, HYD_C',
  'detail_lines': ['2900000100531 - 2900000100539']},
 {'name': 'HYD DEGD A',
  'severities': ['caution'],
  'system': 'HYD',
  'subsystem': 'HYD_A',
  'detail_lines': ['2900000199060']},
 {'name': 'HYD DEGD B',
  'severities': ['caution'],
  'system': 'HYD',
  'subsystem': 'HYD_B',
  'detail_lines': ['2900000199061']},
 {'name': 'HYD DEGD DUAL',
  'severities': ['caution'],
  'system': 'HYD',
  'subsystem': 'HYD_C',
  'detail_lines': ['2900000199060, 2900000199061']},
 {'name': 'HYD FAIL A',
  'severities': ['caution'],
  'system': 'HYD',
  'subsystem': 'HYD_A',
  'detail_lines': ['2900000103060, 2900000199058']},
 {'name': 'HYD FAIL B',
  'severities': ['caution'],
  'system': 'HYD',
  'subsystem': 'HYD_B',
  'detail_lines': ['2900000103062, 2900000199059']},
 {'name': 'HYD FAIL DUAL',
  'severities': ['warning'],
  'system': 'HYD',
  'subsystem': 'HYD_C',
  'detail_lines': ['2900000103062, 2900000199059']},
 {'name': 'HYD FLUID A',
  'severities': ['caution'],
  'system': 'HYD',
  'subsystem': 'HYD_A',
  'detail_lines': ['2900000190344']},
 {'name': 'HYD FLUID B',
  'severities': ['caution'],
  'system': 'HYD',
  'subsystem': 'HYD_B',
  'detail_lines': ['2900000190345']},
 {'name': 'HYD HOT',
  'severities': ['caution'],
  'system': 'HYD',
  'subsystem': 'HYD_C',
  'detail_lines': ['2900000100530']},
 {'name': 'ICP DEGD',
  'severities': ['advisory'],
  'system': 'MSP',
  'subsystem': 'ICP',
  'detail_lines': ['4220010190006 - 4220010190029']},
 {'name': 'IFF DEGD MODE C',
  'severities': ['advisory'],
  'system': 'COM_NAV',
  'subsystem': 'CNI',
  'detail_lines': ['4800000001058 - 4800000204002']},
 {'name': 'INS DEGD',
  'severities': ['caution'],
  'system': 'COM_NAV',
  'subsystem': 'INS',
  'detail_lines': ['4821010100101 - 4821010100999']},
 {'name': 'INS FAIL',
  'severities': ['caution'],
  'system': 'COM_NAV',
  'subsystem': 'INS',
  'detail_lines': ['4821010100101 - 4821010100999']},
 {'name': 'IPP COMBUST FAIL',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'IPPELEC',
  'detail_lines': ['2100000100400 - 2116010100505']},
 {'name': 'IPP CTRL HOT',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'IPPELEC',
  'detail_lines': ['2116010100558 - 2116010100726']},
 {'name': 'IPP DOOR OPEN',
  'severities': ['caution'],
  'system': 'PTMS',
  'subsystem': 'IPPELEC',
  'detail_lines': ['2900000103052']},
 {'name': 'IPP FAIL',
  'severities': ['warning'],
  'system': 'PTMS',
  'subsystem': 'IPPELEC',
  'detail_lines': ['2116010100558 - 2116010100726']},
 {'name': 'IRST DEGD',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'ESM',
  'detail_lines': ['9940000000000 - 9949999999999']},
 {'name': 'IRST FAIL',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'ESM',
  'detail_lines': ['9940000000000 - 9949999999999']},
 {'name': 'JOKER', 'severities': ['caution'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'LADDER UNLOCK', 'severities': ['caution'], 'system': '', 'subsystem': '', 'detail_lines': ['No HRC']},
 {'name': 'LASER ARM CTRL',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'ESM',
  'detail_lines': ['9940000000000 - 9949999999999']},
 {'name': 'LASER DEGD',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'ESM',
  'detail_lines': ['9940000000000 - 9949999999999']},
 {'name': 'LASER FAIL',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'ESM',
  'detail_lines': ['9940000000000 - 9949999999999']},
 {'name': 'LEF LOCK',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'LEFAS',
  'detail_lines': ['2751000121510 - 2783000123531']},
 {'name': 'LST DEGD',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'ESM',
  'detail_lines': ['9940000000000 - 9949999999999']},
 {'name': 'LST FAIL',
  'severities': ['advisory'],
  'system': 'EW',
  'subsystem': 'ESM',
  'detail_lines': ['9940000000000 - 9949999999999']},
 {'name': 'NAV DEGD',
  'severities': ['advisory'],
  'system': 'COM_NAV',
  'subsystem': 'CNI',
  'detail_lines': ['4821011000001 - 4821011540003']},
 {'name': 'NWS DEGD',
  'severities': ['caution'],
  'system': 'GEAR',
  'subsystem': 'NWS',
  'detail_lines': ['3250000199055 - 3250000299003']},
 {'name': 'NWS FAIL',
  'severities': ['caution'],
  'system': 'GEAR',
  'subsystem': 'NWS',
  'detail_lines': ['3250000199055 - 3250000299003']},
 {'name': 'OBOGS FAIL',
  'severities': ['caution'],
  'system': 'LIF_SUP',
  'subsystem': 'OBOGS',
  'detail_lines': ['3500000100200 - 3500000100217']},
 {'name': 'OVERSPEED GEAR',
  'severities': ['caution'],
  'system': 'GEAR',
  'subsystem': 'All: GEAR_L, GEAR_N, GEAR_R',
  'detail_lines': ['5300000911641']},
 {'name': 'OXYGEN CRITICAL',
  'severities': ['warning'],
  'system': 'LIF_SUP',
  'subsystem': 'BOS',
  'detail_lines': ['3500000100216']},
 {'name': 'PARKING BRAKE ON', 'severities': ['advisory'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'PBA FAIL',
  'severities': ['advisory'],
  'system': 'LIF_SUP',
  'subsystem': 'BOS',
  'detail_lines': ['3500000100203 - 3500000100411']},
 {'name': 'PMD FAIL', 'severities': ['caution'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'RADAR DEGD', 'severities': ['advisory'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'RADAR FAIL',
  'severities': ['advisory'],
  'system': 'RADAR',
  'subsystem': 'RADAR',
  'detail_lines': ['9460000000000 - 9470000201700']},
 {'name': 'RADAR INHIB FAIL', 'severities': ['caution'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'REFUEL DOOR',
  'severities': ['caution'],
  'system': 'FUEL',
  'subsystem': 'REFUEL',
  'detail_lines': ['2900000103053']},
 {'name': 'RUDDER FAIL DUAL',
  'severities': ['warning'],
  'system': 'FCS',
  'subsystem': 'EHAS',
  'detail_lines': ['2432050103857']},
 {'name': 'SFD ATTITUDE', 'severities': ['caution'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'SMS',
  'severities': ['caution'],
  'system': 'HYD',
  'subsystem': 'WBDD',
  'detail_lines': ['9431010101000 - 9436040100105']},
 {'name': 'SMS GROUND SAFE',
  'severities': ['advisory', 'caution'],
  'system': 'HYD',
  'subsystem': 'WBDD',
  'detail_lines': ['9410001100028']},
 {'name': 'SMS LOAD INVALID',
  'severities': ['caution'],
  'system': 'MSP',
  'subsystem': 'PMD',
  'detail_lines': ['9436010100105']},
 {'name': 'STAB FAIL',
  'severities': ['warning'],
  'system': 'FCS',
  'subsystem': 'EHAS',
  'detail_lines': ['2432050103814 - 2432052103817, 2741000121099 - 2742000122631']},
 {'name': 'STICK HOT', 'severities': ['caution'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'STICK JAMMED',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'STICK',
  'detail_lines': ['2713012101033']},
 {'name': 'TEST', 'severities': ['warning'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'TEST', 'severities': ['caution'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'TEST', 'severities': ['advisory'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'TFLIR DEGD',
  'severities': ['advisory'],
  'system': 'EOTS',
  'subsystem': 'EOTS',
  'detail_lines': ['9940000000000 - 9949999999999']},
 {'name': 'TFLIR FAIL',
  'severities': ['advisory'],
  'system': 'EOTS',
  'subsystem': 'EOTS',
  'detail_lines': ['9940000000000 - 9949999999999']},
 {'name': 'THROTTLE HOT', 'severities': ['caution'], 'system': '', 'subsystem': '', 'detail_lines': ['NO HRC']},
 {'name': 'THROTTLE JAMMED',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'THROTL',
  'detail_lines': ['2713012101039']},
 {'name': 'THROTTLE PASSIVE',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'THROTL',
  'detail_lines': ['2713012101001']},
 {'name': 'TNS HOT',
  'severities': ['caution'],
  'system': 'COM_NAV',
  'subsystem': 'CNI',
  'detail_lines': ['3420000100141']},
 {'name': 'TRIM FAIL',
  'severities': ['caution'],
  'system': 'FCS',
  'subsystem': 'AIRDAT',
  'detail_lines': ['2713000101004']},
 {'name': 'VS BIT NO GO',
  'severities': ['caution'],
  'system': 'VSP',
  'subsystem': 'VMC',
  'detail_lines': ['2700000299013 - 4620030291320']},
 {'name': 'VS BIT RUNNING', 'severities': ['advisory'], 'system': '', 'subsystem': '', 'detail_lines': []},
 {'name': 'V VEL DISAGREE',
  'severities': ['caution'],
  'system': 'COM_NAV',
  'subsystem': 'CNI',
  'detail_lines': ['4821010100100 - 4821010100999']},
 {'name': 'VMC DEGD A',
  'severities': ['caution'],
  'system': 'VSP',
  'subsystem': 'VMC',
  'detail_lines': ['4610010100104 - 4610018200217']},
 {'name': 'VMC DEGD B',
  'severities': ['caution'],
  'system': 'VSP',
  'subsystem': 'VMC',
  'detail_lines': ['4610010100104 - 4610018200217']},
 {'name': 'VMC DEGD C',
  'severities': ['caution'],
  'system': 'VSP',
  'subsystem': 'VMC',
  'detail_lines': ['4610010100104 - 4610018200217']},
 {'name': 'WPN DOOR', 'severities': ['caution'], 'system': '', 'subsystem': '', 'detail_lines': ['9421000191002']}]


_REFERENCE_ICAWS_TOC_ALERTS: List[Dict[str, str]] = [
 {'name': 'AFTERBURNER FAIL', 'severity': 'caution', 'page': 'EP-47'},
 {'name': 'AIR DATA DEGD', 'severity': 'caution', 'page': 'EP-47'},
 {'name': 'AIR DATA FAIL', 'severity': 'caution', 'page': 'EP-48'},
 {'name': 'AIR DATA HEATER', 'severity': 'caution', 'page': 'EP-50'},
 {'name': 'AMD FAIL', 'severity': 'caution', 'page': 'EP-50'},
 {'name': 'AUDIO FAIL', 'severity': 'caution', 'page': 'EP-50'},
 {'name': 'BATT FAIL 270V', 'severity': 'caution', 'page': 'EP-51'},
 {'name': 'BATT FAIL 28V', 'severity': 'caution', 'page': 'EP-52'},
 {'name': 'BATT LO 270V', 'severity': 'warning', 'page': 'EP-3'},
 {'name': 'BATT LO 270V', 'severity': 'caution', 'page': 'EP-52'},
 {'name': 'BATT LO 28V', 'severity': 'warning', 'page': 'EP-4'},
 {'name': 'BATT LO 28V', 'severity': 'caution', 'page': 'EP-53'},
 {'name': 'BLD LEAK ENG', 'severity': 'warning', 'page': 'EP-5'},
 {'name': 'BLD LEAK IPP', 'severity': 'warning', 'page': 'EP-6'},
 {'name': 'BOS DISABLED', 'severity': 'caution', 'page': 'EP-54'},
 {'name': 'BOS LO', 'severity': 'caution', 'page': 'EP-55'},
 {'name': 'BOS ON', 'severity': 'caution', 'page': 'EP-301'},
 {'name': 'BOS OVERRIDE ON', 'severity': 'caution', 'page': 'EP-56'},
 {'name': 'BOS SERVICE', 'severity': 'advisory', 'page': 'EP-301'},
 {'name': 'BRAKE DEGD', 'severity': 'caution', 'page': 'EP-57'},
 {'name': 'BRAKE FAIL', 'severity': 'caution', 'page': 'EP-58'},
 {'name': 'BUR DEGD', 'severity': 'advisory', 'page': 'EP-301'},
 {'name': 'BUR FAIL', 'severity': 'advisory', 'page': 'EP-301'},
 {'name': 'BUR HOT', 'severity': 'caution', 'page': 'EP-59'},
 {'name': 'DELAMINATION', 'severity': 'warning', 'page': 'EP-245'},
 {'name': 'CANOPY UNLOCKED', 'severity': 'caution', 'page': 'EP-62'},
 {'name': 'CANOPY UNLOCKED', 'severity': 'advisory', 'page': 'EP-303'},
 {'name': 'CG FORWARD', 'severity': 'caution', 'page': 'EP-64'},
 {'name': 'CG LATERAL', 'severity': 'caution', 'page': 'EP-66'},
 {'name': 'CHK LST DEGD', 'severity': 'caution', 'page': 'EP-67'},
 {'name': 'CM DEGD', 'severity': 'caution', 'page': 'EP-303'},
 {'name': 'CM DOOR', 'severity': 'caution', 'page': 'EP-303'},
 {'name': 'CM FAIL', 'severity': 'caution', 'page': 'EP-303'},
 {'name': 'CM HOT LEFT', 'severity': 'caution', 'page': 'EP-67'},
 {'name': 'CM HOT RIGHT', 'severity': 'caution', 'page': 'EP-67'},
 {'name': 'CM IR EMER', 'severity': 'caution', 'page': 'EP-67'},
 {'name': 'CM TO DOOR', 'severity': 'caution', 'page': 'EP-67'},
 {'name': 'CM TO FAIL DEPL', 'severity': 'caution', 'page': 'EP-67'},
 {'name': 'CNI FAIL IFF', 'severity': 'warning', 'page': 'EP-68'},
 {'name': 'CNI FAIL ILS', 'severity': 'caution', 'page': 'EP-303'},
 {'name': 'CNI FAIL ITM', 'severity': 'caution', 'page': 'EP-3-3'},
 {'name': 'CNI HOT A', 'severity': 'caution', 'page': 'EP-68'},
 {'name': 'CNI HOT AC', 'severity': 'caution', 'page': 'EP-68'},
 {'name': 'CNI HOT E', 'severity': 'caution', 'page': 'EP-69'},
 {'name': 'CNI HOT FUNC', 'severity': 'caution', 'page': 'EP-69'},
 {'name': 'CNI RACK FAIL A', 'severity': 'caution', 'page': 'EP-69'},
 {'name': 'CNI RACK FAIL B', 'severity': 'caution', 'page': 'EP-70'},
 {'name': 'CNVTR FAIL DUAL', 'severity': 'warning', 'page': 'EP-7'},
 {'name': 'CNVTR HOT', 'severity': 'warning', 'page': 'EP-10'},
 {'name': 'COLD LOOP TEMP', 'severity': 'caution', 'page': 'EP-71'},
 {'name': 'COOL DEGD EHA', 'severity': 'caution', 'page': 'EP-71'},
 {'name': 'COOL DEGD FCS CH', 'severity': 'caution', 'page': 'EP-71'},
 {'name': 'COOL FAIL EHA', 'severity': 'caution', 'page': 'EP-72'},
 {'name': 'COOL FAIL ENG', 'severity': 'caution', 'page': 'EP-73'},
 {'name': 'COOL FAIL FCS CH', 'severity': 'caution', 'page': 'EP-74'},
 {'name': 'COOL FAIL IPP', 'severity': 'caution', 'page': 'EP-75'},
 {'name': 'DAS DEGD', 'severity': 'caution', 'page': 'EP-305'},
 {'name': 'DAS FAIL', 'severity': 'warning', 'page': 'EP-305'},
 {'name': 'DISPLAY DEGD', 'severity': 'caution', 'page': 'EP-77'},
 {'name': 'DISPLAY HOT HMD', 'severity': 'caution', 'page': 'EP-78'},
 {'name': 'DISPLAY HOT L', 'severity': 'caution', 'page': 'EP-79'},
 {'name': 'DISPLAY HOT R', 'severity': 'caution', 'page': 'EP-79'},
 {'name': 'DMCH DEGD', 'severity': 'caution', 'page': 'EP-80'},
 {'name': 'DMCH FAIL', 'severity': 'caution', 'page': 'EP-80'},
 {'name': 'ENG A-ICE FAIL', 'severity': 'caution', 'page': 'EP-81'},
 {'name': 'ENG COMM DEGD', 'severity': 'caution', 'page': 'EP-84'},
 {'name': 'ENG COMM FAIL', 'severity': 'warning', 'page': 'EP-11'},
 {'name': 'ENG CTRL FAIL', 'severity': 'warning', 'page': 'EP-12'},
 {'name': 'ENG DEGD', 'severity': 'caution', 'page': 'EP-85'},
 {'name': 'ENG FADEC FAIL', 'severity': 'caution', 'page': 'EP-86'},
 {'name': 'ENG FADEC HOT', 'severity': 'caution', 'page': 'EP-86'},
 {'name': 'ENG FAULT', 'severity': 'advisory', 'page': 'EP-307'},
 {'name': 'ENG ICE DETECTED', 'severity': 'caution', 'page': 'EP-87'},
 {'name': 'ENG ICE DETECTED', 'severity': 'advisory', 'page': 'EP-307'},
 {'name': 'ENG LAST CH', 'severity': 'caution', 'page': 'EP-88'},
 {'name': 'ENG LIMITS', 'severity': 'caution', 'page': 'EP-89'},
 {'name': 'ENG OIL', 'severity': 'caution', 'page': 'EP-90'},
 {'name': 'ENG OIL HOT', 'severity': 'caution', 'page': 'EP-91'},
 {'name': 'ENG STALL', 'severity': 'caution', 'page': 'EP-92'},
 {'name': 'ENG THRUST LO', 'severity': 'caution', 'page': 'EP-92'},
 {'name': 'EOTS DEGD', 'severity': 'advisory', 'page': 'EP-308'},
 {'name': 'EOTS FAIL', 'severity': 'warning', 'page': 'EP-308'},
 {'name': 'EPS COMM DEGD', 'severity': 'caution', 'page': 'EP-93'},
 {'name': 'EPS DEGD', 'severity': 'caution', 'page': 'EP-94'},
 {'name': 'EPS FAIL 270V', 'severity': 'caution', 'page': 'EP-98'},
 {'name': 'EPS FAIL 28V', 'severity': 'caution', 'page': 'EP-101'},
 {'name': 'EPS FAULT', 'severity': 'caution', 'page': 'EP-104'},
 {'name': 'EW FAIL', 'severity': 'advisory', 'page': 'EP-308'},
 {'name': 'EW HOT', 'severity': 'caution', 'page': 'EP-104'},
 {'name': 'EW HOT AEM AFT', 'severity': 'caution', 'page': 'EP-104'},
 {'name': 'EW HOT AEM FWD', 'severity': 'caution', 'page': 'EP-104'},
 {'name': 'EXT TANK PRESS', 'severity': 'caution', 'page': 'EP-100'},
 {'name': 'FCS ALIGN TNS', 'severity': 'advisory', 'page': 'EP-309'},
 {'name': 'FCS CG DEGD', 'severity': 'caution', 'page': 'EP-105'},
 {'name': 'FCS CH FAIL A', 'severity': 'caution', 'page': 'EP-106'},
 {'name': 'FCS CH FAIL B', 'severity': 'caution', 'page': 'EP-111'},
 {'name': 'FCS CH FAIL C', 'severity': 'caution', 'page': 'EP-115'},
 {'name': 'FCS CH HOT A', 'severity': 'caution', 'page': 'EP-119'},
 {'name': 'FCS CH HOT B', 'severity': 'caution', 'page': 'EP-119'},
 {'name': 'FCS CH HOT C', 'severity': 'caution', 'page': 'EP-119'},
 {'name': 'FCS DATA FAIL', 'severity': 'warning', 'page': 'EP-13'},
 {'name': 'FCS DEGD', 'severity': 'caution', 'page': 'EP-119'},
 {'name': 'FCS EHA COLD', 'severity': 'caution', 'page': 'EP-119'},
 {'name': 'FCS EHA HOT', 'severity': 'caution', 'page': 'EP-120'},
 {'name': 'FCS FAULT', 'severity': 'caution', 'page': 'EP-312'},
 {'name': 'FCS FUEL COMM', 'severity': 'caution', 'page': 'EP-120'},
 {'name': 'FCS LAST CH', 'severity': 'caution', 'page': 'EP-121'},
 {'name': 'FCS POWER LIMIT', 'severity': 'caution', 'page': 'EP-121'},
 {'name': 'FCS POWER LIMIT', 'severity': 'warning', 'page': 'EP-16'},
 {'name': 'FCS SURFACE DEGD', 'severity': 'caution', 'page': 'EP-122'},
 {'name': 'FCS SURFACE FAIL', 'severity': 'caution', 'page': 'EP-123'},
 {'name': 'FCS VEL DEGD', 'severity': 'caution', 'page': 'EP-125'},
 {'name': 'FIRE CM BAY', 'severity': 'warning', 'page': 'EP-16'},
 {'name': 'FIRE ENG', 'severity': 'warning', 'page': 'EP-17'},
 {'name': 'FIRE GEAR', 'severity': 'warning', 'page': 'EP-17'},
 {'name': 'FIRE IPP', 'severity': 'warning', 'page': 'EP-18'},
 {'name': 'FIRE WPN BAY L', 'severity': 'warning', 'page': 'EP-19'},
 {'name': 'FIRE WPN BAY R', 'severity': 'warning', 'page': 'EP-19'},
 {'name': 'FPS DETECT DEGD', 'severity': 'caution', 'page': 'EP-128'},
 {'name': 'FPS DISCHARGE', 'severity': 'caution', 'page': 'EP-128'},
 {'name': 'FPS SUPPRESS DEGD', 'severity': 'caution', 'page': 'EP-128'},
 {'name': 'FRIU HW CONFIG', 'severity': 'advisory', 'page': 'EP-314'},
 {'name': 'FUEL BOOST LO', 'severity': 'caution', 'page': 'EP-129'},
 {'name': 'FUEL BOOST PUMP', 'severity': 'caution', 'page': 'EP-129'},
 {'name': 'FUEL CRITICAL', 'severity': 'warning', 'page': 'EP-23'},
 {'name': 'FUEL DEGD', 'severity': 'caution', 'page': 'EP-130'},
 {'name': 'FUEL DUMP OPEN', 'severity': 'caution', 'page': 'EP-132'},
 {'name': 'FUEL FEED TANK', 'severity': 'caution', 'page': 'EP-133'},
 {'name': 'FUEL HOT', 'severity': 'caution', 'page': 'EP-134'},
 {'name': 'FUEL LEAK', 'severity': 'warning', 'page': 'EP-24'},
 {'name': 'FUEL RECIRC', 'severity': 'advisory', 'page': 'EP-134'},
 {'name': 'FUEL TANK ISO', 'severity': 'caution', 'page': 'EP-134'},
 {'name': 'FUEL TANK PRESS', 'severity': 'caution', 'page': 'EP-135'},
 {'name': 'FUEL VENT', 'severity': 'caution', 'page': 'EP-137'},
 {'name': 'GCAS ALT DEGD', 'severity': 'advisory', 'page': 'EP-315'},
 {'name': 'GEAR DEGD', 'severity': 'caution', 'page': 'EP-139'},
 {'name': 'GEAR FAIL', 'severity': 'caution', 'page': 'EP-139'},
 {'name': 'GEAR UNSAFE LDG', 'severity': 'warning', 'page': 'EP-268'},
 {'name': 'GEN FAIL 1', 'severity': 'caution', 'page': 'EP-140'},
 {'name': 'GEN FAIL 1&2', 'severity': 'warning', 'page': 'EP-142'},
 {'name': 'GEN FAIL 2', 'severity': 'caution', 'page': 'EP-144'},
 {'name': 'GEN FAIL 3', 'severity': 'caution', 'page': 'EP-146'},
 {'name': 'GEN FAIL ALL', 'severity': 'warning', 'page': 'EP-27'},
 {'name': 'GEN HOT 3', 'severity': 'caution', 'page': 'EP-146'},
 {'name': 'GEN OIL FAIL 1&2', 'severity': 'caution', 'page': 'EP-147'},
 {'name': 'GEN OIL HOT 1&2', 'severity': 'caution', 'page': 'EP-148'},
 {'name': 'GEN OIL HOT', 'severity': 'caution', 'page': 'EP-148'},
 {'name': 'GPS KEYS', 'severity': 'advisory', 'page': 'EP-315'},
 {'name': 'GUN NOT SAFE', 'severity': 'caution', 'page': 'EP-149'},
 {'name': 'HDG DISAGREE', 'severity': 'caution', 'page': 'EP-151'},
 {'name': 'HMD FAIL', 'severity': 'warning', 'page': 'EP-273'},
 {'name': 'HOOK FAIL', 'severity': 'caution', 'page': 'EP-252'},
 {'name': 'HOT BRAKES', 'severity': 'caution', 'page': 'EP-274'},
 {'name': 'HOTAS FAULT', 'severity': 'caution', 'page': 'EP-317'},
 {'name': 'HUNG STORES', 'severity': 'caution', 'page': 'EP-275'},
 {'name': 'HYD COLD', 'severity': 'caution', 'page': 'EP-152'},
 {'name': 'HYD DEGD A', 'severity': 'caution', 'page': 'EP-153'},
 {'name': 'HYD DEGD B', 'severity': 'caution', 'page': 'EP-154'},
 {'name': 'HYD DEGD DUAL', 'severity': 'caution', 'page': 'EP-155'},
 {'name': 'HYD FAIL A', 'severity': 'caution', 'page': 'EP-157'},
 {'name': 'HYD FAIL B', 'severity': 'caution', 'page': 'EP-158'},
 {'name': 'HYD FAIL DUAL', 'severity': 'warning', 'page': 'EP-31'},
 {'name': 'HYD FLUID A', 'severity': 'caution', 'page': 'EP-160'},
 {'name': 'HYD FLUID B', 'severity': 'caution', 'page': 'EP-160'},
 {'name': 'HYD HOT', 'severity': 'caution', 'page': 'EP-161'},
 {'name': 'ICAWS FAIL', 'severity': 'caution', 'page': 'EP-163'},
 {'name': 'ICP DEGD', 'severity': 'caution', 'page': 'EP-319'},
 {'name': 'ICP HOT A', 'severity': 'caution', 'page': 'EP-323'},
 {'name': 'ICP HOT B', 'severity': 'caution', 'page': 'EP-163'},
 {'name': 'INERT DEGD', 'severity': 'caution', 'page': 'EP-321'},
 {'name': 'INS DEGD', 'severity': 'caution', 'page': 'EP-164'},
 {'name': 'INS FAIL', 'severity': 'caution', 'page': 'EP-165'},
 {'name': 'INS FL DRIFT', 'severity': 'caution', 'page': 'EP-322'},
 {'name': 'IPP COMBUST FAIL', 'severity': 'caution', 'page': 'EP-166'},
 {'name': 'IPP COMBUST ON', 'severity': 'advisory', 'page': 'EP-323'},
 {'name': 'IPP CTRL HOT', 'severity': 'caution', 'page': 'EP-166'},
 {'name': 'IPP DOOR OPEN', 'severity': 'caution', 'page': 'EP-166'},
 {'name': 'IPP FAIL', 'severity': 'warning', 'page': 'EP-33'},
 {'name': 'IRST DEGD', 'severity': 'caution', 'page': 'EP-324'},
 {'name': 'IRST FAIL', 'severity': 'warning', 'page': 'EP-324'},
 {'name': 'LADDER UNLOCKED', 'severity': 'caution', 'page': 'EP-167'},
 {'name': 'LADDER UNLOCKED', 'severity': 'advisory', 'page': 'EP-325'},
 {'name': 'LASER ARM CTRL', 'severity': 'caution', 'page': 'EP-325'},
 {'name': 'LASER DEGD', 'severity': 'caution', 'page': 'EP-326'},
 {'name': 'LASER FAIL', 'severity': 'warning', 'page': 'EP-326'},
 {'name': 'LEF LOCK', 'severity': 'caution', 'page': 'EP-168'},
 {'name': 'LST DEGD', 'severity': 'caution', 'page': 'EP-327'},
 {'name': 'LST FAIL', 'severity': 'warning', 'page': 'EP-327'},
 {'name': 'NAV DEGD', 'severity': 'caution', 'page': 'EP-329'},
 {'name': 'NWS DEGD', 'severity': 'caution', 'page': 'EP-169'},
 {'name': 'NWS FAIL', 'severity': 'caution', 'page': 'EP-169'},
 {'name': 'OBIGGS FAIL', 'severity': 'caution', 'page': 'EP-331'},
 {'name': 'OBOGS BIT', 'severity': 'caution', 'page': 'EP-171'},
 {'name': 'OBOGS BIT', 'severity': 'caution', 'page': 'EP-331'},
 {'name': 'OBOGS FAIL', 'severity': 'caution', 'page': 'EP-171'},
 {'name': 'OBOGS PRESS LO', 'severity': 'advisory', 'page': 'EP-331'},
 {'name': 'OFF LOAD FAIL', 'severity': 'caution', 'page': 'EP-172'},
 {'name': 'OVER G', 'severity': 'caution', 'page': 'EP-332'},
 {'name': 'OVERSPEED', 'severity': 'caution', 'page': 'EP-172'},
 {'name': 'OVERSPEED AAR', 'severity': 'caution', 'page': 'EP-172'},
 {'name': 'OVERSPEED GEAR', 'severity': 'caution', 'page': 'EP-172'},
 {'name': 'OVERSPEED HOOK', 'severity': 'caution', 'page': 'EP-173'},
 {'name': 'OXY FLOW DEGD', 'severity': 'caution', 'page': 'EP-173'},
 {'name': 'OXY FLOW DEGD', 'severity': 'advisory', 'page': 'EP-332'},
 {'name': 'OXYGEN CRITICAL', 'severity': 'warning', 'page': 'EP-37'},
 {'name': 'PARKING BRAKE ON', 'severity': 'caution', 'page': 'EP-175'},
 {'name': 'PBA FAIL', 'severity': 'caution', 'page': 'EP-175'},
 {'name': 'PBA FAIL', 'severity': 'caution', 'page': 'EP-333'},
 {'name': 'PMD FAIL', 'severity': 'caution', 'page': 'EP-175'},
 {'name': 'RADAR COOL DEGD', 'severity': 'advisory', 'page': 'EP-335'},
 {'name': 'RADAR DEGD', 'severity': 'advisory', 'page': 'EP-335'},
 {'name': 'RADAR FAIL', 'severity': 'caution', 'page': 'EP-336'},
 {'name': 'RADAR HOT', 'severity': 'caution', 'page': 'EP-177'},
 {'name': 'RADAR INHIB FAIL', 'severity': 'caution', 'page': 'EP-177'},
 {'name': 'RAM AIR FAIL', 'severity': 'caution', 'page': 'EP-177'},
 {'name': 'REFUEL DOOR', 'severity': 'caution', 'page': 'EP-178'},
 {'name': 'RIO FAIL 1A', 'severity': 'caution', 'page': 'EP-179'},
 {'name': 'RIO FAIL 1B', 'severity': 'caution', 'page': 'EP-181'},
 {'name': 'RIO FAIL 2B', 'severity': 'caution', 'page': 'EP-182'},
 {'name': 'RIO FAIL 2C', 'severity': 'caution', 'page': 'EP-184'},
 {'name': 'RIO FAIL 3A', 'severity': 'caution', 'page': 'EP-186'},
 {'name': 'RIO FAIL 3B', 'severity': 'caution', 'page': 'EP-188'},
 {'name': 'RIO FAIL 3C', 'severity': 'caution', 'page': 'EP-190'},
 {'name': 'RIO FAIL 4A', 'severity': 'caution', 'page': 'EP-192'},
 {'name': 'RIO FAIL 4B', 'severity': 'caution', 'page': 'EP-195'},
 {'name': 'RIO FAIL 4C', 'severity': 'caution', 'page': 'EP-197'},
 {'name': 'RIO IND FAIL 1A', 'severity': 'caution', 'page': 'EP-199'},
 {'name': 'RIO IND FAIL 1B', 'severity': 'caution', 'page': 'EP-200'},
 {'name': 'RIO IND FAIL 2B', 'severity': 'caution', 'page': 'EP-200'},
 {'name': 'RIO IND FAIL 2C', 'severity': 'caution', 'page': 'EP-200'},
 {'name': 'RIO IND FAIL 3A', 'severity': 'caution', 'page': 'EP-199'},
 {'name': 'RIO IND FAIL 3B', 'severity': 'caution', 'page': 'EP-200'},
 {'name': 'RIO IND FAIL 3C', 'severity': 'caution', 'page': 'EP-202'},
 {'name': 'RIO IND FAIL 4A', 'severity': 'caution', 'page': 'EP-199'},
 {'name': 'RIO IND FAIL 4B', 'severity': 'caution', 'page': 'EP-200'},
 {'name': 'RIO IND FAIL 4C', 'severity': 'caution', 'page': 'EP-202'},
 {'name': 'RUDDER FAIL DUAL', 'severity': 'warning', 'page': 'EP-39'},
 {'name': 'SEAT NOT ARMED', 'severity': 'caution', 'page': 'EP-203'},
 {'name': 'SEAT NOT ARMED', 'severity': 'advisory', 'page': 'EP-207'},
 {'name': 'SFD ATTITUDE', 'severity': 'caution', 'page': 'EP-203'},
 {'name': 'SFD HDG DEGD', 'severity': 'caution', 'page': 'EP-203'},
 {'name': 'SMS', 'severity': 'caution', 'page': 'EP-204'},
 {'name': 'SMS GROUND SAFE', 'severity': 'caution', 'page': 'EP-337'},
 {'name': 'SMS LOAD INVALID', 'severity': 'caution', 'page': 'EP-305'},
 {'name': 'SMS STA01 UNLK', 'severity': 'caution', 'page': 'EP-206'},
 {'name': 'SMS STA05 UNLK', 'severity': 'caution', 'page': 'EP-206'},
 {'name': 'SMS STA07 UNLK', 'severity': 'caution', 'page': 'EP-206'},
 {'name': 'SMS STA11 UNLK', 'severity': 'caution', 'page': 'EP-206'},
 {'name': 'SPA BATT FAIL', 'severity': 'caution', 'page': 'EP-337'},
 {'name': 'STAB FAIL', 'severity': 'warning', 'page': 'EP-41'},
 {'name': 'STICK HOT', 'severity': 'caution', 'page': 'EP-207'},
 {'name': 'STICK JAMMED', 'severity': 'caution', 'page': 'EP-207'},
 {'name': 'STICK PASSIVE', 'severity': 'caution', 'page': 'EP-207'},
 {'name': 'SYSTEM SEC DEGD', 'severity': 'advisory', 'page': 'EP-338'},
 {'name': 'SYSTEM SEC FAIL', 'severity': 'advisory', 'page': 'EP-339'},
 {'name': 'TD DEPLOYED', 'severity': 'advisory', 'page': 'EP-209'},
 {'name': 'TFLIR DEGD', 'severity': 'caution', 'page': 'EP-341'},
 {'name': 'TFLIR FAIL', 'severity': 'warning', 'page': 'EP-341'},
 {'name': 'TFLIR HOT', 'severity': 'caution', 'page': 'EP-209'},
 {'name': 'THROTTLE HOT', 'severity': 'caution', 'page': 'EP-209'},
 {'name': 'THROTTLE JAMMED', 'severity': 'caution', 'page': 'EP-210'},
 {'name': 'THROTTLE PASSIVE', 'severity': 'caution', 'page': 'EP-210'},
 {'name': 'TNS HOT', 'severity': 'caution', 'page': 'EP-211'},
 {'name': 'TRIM FAIL', 'severity': 'caution', 'page': 'EP-211'},
 {'name': 'V VEL DISAGREE', 'severity': 'caution', 'page': 'EP-228'},
 {'name': 'VMC DEGD A', 'severity': 'caution', 'page': 'EP-213'},
 {'name': 'VMC DEGD B', 'severity': 'caution', 'page': 'EP-218'},
 {'name': 'VMC DEGD C', 'severity': 'caution', 'page': 'EP-222'},
 {'name': 'VS BIT NO GO', 'severity': 'advisory', 'page': 'EP-225'},
 {'name': 'VS BIT NO GO', 'severity': 'advisory', 'page': 'EP-343'},
 {'name': 'VS BIT RUNNING', 'severity': 'advisory', 'page': 'EP-344'},
 {'name': 'WPN DEGD', 'severity': 'caution', 'page': 'EP-229'},
 {'name': 'WPN DOOR', 'severity': 'caution', 'page': 'EP-229'},
 {'name': 'WPN HOT', 'severity': 'caution', 'page': 'EP-230'},
 {'name': 'ZEROIZE DISABLED', 'severity': 'caution', 'page': 'EP-231'},
]


def _apply_reference_icaws_toc_overlay() -> None:
    severity_order = {"warning": 0, "caution": 1, "advisory": 2}
    desired: Dict[str, Dict[str, object]] = {}
    for row in _REFERENCE_ICAWS_TOC_ALERTS:
        name = str(row.get("name", "")).strip().lstrip(">").strip()
        sev = str(row.get("severity", "")).strip().lower()
        page = str(row.get("page", "")).strip()
        if name == "" or sev not in severity_order:
            continue
        key = name.upper()
        rec = desired.setdefault(key, {"name": name, "severities": [], "pages": []})
        sevs = rec["severities"]
        pages = rec["pages"]
        if isinstance(sevs, list) and sev not in sevs:
            sevs.append(sev)
            sevs.sort(key=lambda item: severity_order.get(str(item), 99))
        if isinstance(pages, list) and page != "" and page not in pages:
            pages.append(page)

    by_name: Dict[str, Dict[str, object]] = {}
    for entry in HRC_ALERT_DEFS:
        if not isinstance(entry, dict):
            continue
        name = str(entry.get("name", "")).strip()
        if name != "":
            by_name.setdefault(name.upper(), entry)

    for rec in desired.values():
        name = str(rec.get("name", "")).strip()
        if name == "":
            continue
        sevs_raw = rec.get("severities", [])
        pages_raw = rec.get("pages", [])
        sevs = [str(s) for s in sevs_raw] if isinstance(sevs_raw, list) else []
        pages = [str(p) for p in pages_raw] if isinstance(pages_raw, list) else []
        ref_line = "Reference TOC: " + ", ".join(pages) if len(pages) > 0 else "Reference TOC"
        entry = by_name.get(name.upper())
        if entry is None:
            entry = {"name": name, "severities": list(sevs), "system": "", "subsystem": "", "detail_lines": [ref_line]}
            HRC_ALERT_DEFS.append(entry)
            by_name[name.upper()] = entry
            continue
        entry["severities"] = list(sevs)
        detail_raw = entry.get("detail_lines", [])
        details = [str(item) for item in detail_raw] if isinstance(detail_raw, list) else []
        details = [line for line in details if not line.startswith("Reference TOC")]
        details.append(ref_line)
        entry["detail_lines"] = details


_apply_reference_icaws_toc_overlay()


def hrc_text() -> str:
    lines: List[str] = []
    for entry in HRC_ALERT_DEFS:
        if not isinstance(entry, dict):
            continue
        name = str(entry.get("name", "")).strip()
        sevs_raw = entry.get("severities", [])
        sevs = [str(s).strip().upper() for s in sevs_raw] if isinstance(sevs_raw, list) else []
        system = str(entry.get("system", "")).strip()
        subsystem = str(entry.get("subsystem", "")).strip()
        if name == "" or len(sevs) <= 0:
            continue
        header = f"{name}: {'/'.join(sevs)}"
        if system != "":
            header += f" | {system}"
            if subsystem != "":
                header += f" | {subsystem}"
        lines.append(header)
        details = entry.get("detail_lines", [])
        if isinstance(details, list):
            for d in details:
                lines.append(str(d))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
